language: c++
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty

before_script:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/m/minizip/libminizip1_1.1-8_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/m/minizip/libminizip-dev_1.1-8_amd64.deb
  - sudo dpkg -i /libminizip1_1.1-8_amd64.deb libminizip-dev_1.1-8_amd64.deb
  
script:  make
